### ISSUE TITLE
add address support

### ISSUE THREAD

**Issue by paOol** [bitcoincashjs/cashaddrjs#1]
I was about to use this library but the hash of array integers is a strange parameter.

I was unable to convert an address to the necessary param.

I ended up using https://github.com/bitcoincashjs/bitcoincashjs but it's a very heavy solution for just address translation.

please add support for something like

` address = cashaddr.encode('16w1D5WRVKJuZUsSRzdLp9w3YGcgoxDXb');`

address validation would be nice, but not required.

**Comment by ealmansi** [comment]
Hey @paOol , the following snippet will get your use case covered without the bloat:
```
const bs58check = require("bs58check")
const cashaddr = require("cashaddrjs")

function toCashaddr(address) {
  const [version, ...bytes] = [...bs58check.decode(address)]
  return cashaddr.encode('bitcoincash', 'P2PKH', bytes)
}

function fromCashaddr(address) {
  const version = 0
  const bytes = cashaddr.decode(address).hash
  return bs58check.encode(new Buffer([version].concat(bytes)))
}

console.log(toCashaddr('1LP6t7qqdisMsaWdBxFZiAPqLoekhD28zi'))
// bitcoincash:qr2fsu6h8l4n736g4w0ugnxx0jfenfm84u34rrrx8g

console.log(fromCashaddr('bitcoincash:qr2fsu6h8l4n736g4w0ugnxx0jfenfm84u34rrrx8g'))
// 1LP6t7qqdisMsaWdBxFZiAPqLoekhD28zi
```

You'll need to extend this a little if you also need to cover P2SH addresses or other networks.

That being said, this library is meant to be an implementation of the cashaddr [spec](https://github.com/Bitcoin-UAHF/spec/blob/master/cashaddr.md) and not a general Bitcoin Cash address translation library. Hence, this would be out of scope for now.

**Comment by paOol** [comment]
ty

**Comment by ealmansi** [comment]
@paOol In case you still need this, check this out:

https://github.com/bitcoincashjs/bchaddrjs
