### ISSUE TITLE
Error Correction

### ISSUE THREAD

**Issue by DesWurstes** [bitcoincashjs/cashaddrjs#2]
https://github.com/deadalnix/cashaddressed/blob/master/fixup.d

**Comment by ealmansi** [comment]
This is definitely on the pipeline for v1.

Feel free to send a PR, or else I'll tackle this after introducing typed arrays.

Just a note: error correction should most definitely not be done by default during regular decoding, but rather as optional functionality or a separate procedure all together.

**Comment by ealmansi** [comment]
There seems to be no active interest in this feature. Closing for now; will reopen in the future if it becomes relevant.
