### ISSUE TITLE
Unminified embed-able js

### ISSUE THREAD

**Issue by zquestz** [bitcoincashjs/cashaddrjs#3]
So I have some unique requirements. I am working on https://cashaddress.org and like to make sure all source code is in a single file, in an unminified format since that was the original vision by the bitaddress team.

The project started years ago, but I want to revamp it for the new cashaddr format. Any suggestions for the best way to integrate?

The project is located at https://github.com/theantnest/bccaddress

**Comment by ealmansi** [comment]
@zquestz I've added a [browserified](http://browserify.org/), non-minified, ES5 version of the library into the dist directory:
- https://github.com/bitcoincashjs/cashaddrjs/tree/master/dist/

You could include that file via a script tag, or copy-paste the contents into your monolithic js file and remove the code you don't need.

Let me know if that helps.

**Comment by zquestz** [comment]
This definitely helps. Will play around with the library tomorrow and let you know how it goes. =)
